name: ldb
description: Local Database API on top of SEMBAST API
version: 0.0.1
publish_to: "none"
homepage: https://github.com/RagehAz/ldb.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sembast: ^3.1.1
  path_provider: ^2.0.6
  path: ^1.8.0
  package_info_plus: ^3.0.1
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
